# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-01 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=64, verbose_name='名字')),
            ],
            options={
                'verbose_name_plural': '新闻类别表',
                'db_table': 'cate',
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_time', models.DateTimeField(verbose_name='发表时间')),
                ('new_seenum', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('new_disnum', models.IntegerField(default=0, verbose_name='跟帖次数')),
                ('index_image_url', models.ImageField(default='SOME STRING', upload_to='', verbose_name='新闻列表图片路径')),
                ('new_title', models.CharField(max_length=100, verbose_name='标题')),
                ('new_source', models.TextField(default='Fantasy News', max_length=20, verbose_name='新闻来源')),
                ('digest', models.CharField(default='SOME STRING', max_length=500)),
                ('new_content', models.TextField(verbose_name='新闻内容')),
                ('new_cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='类别', to='index.Cate')),
            ],
            options={
                'verbose_name_plural': '新闻信息表',
                'db_table': 'new',
            },
        ),
    ]
