# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-04 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20191101_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='new_cate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='类别', to='index.Cate'),
            preserve_default=False,
        ),
    ]
