# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-06 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20191104_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_id', models.IntegerField(verbose_name='新闻id')),
                ('like_new_id', models.IntegerField(verbose_name='相似新闻id')),
                ('similarity', models.FloatField(verbose_name='相似度')),
            ],
            options={
                'verbose_name_plural': '新闻相似度表',
                'db_table': 'new_correlation',
            },
        ),
    ]
