# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-06 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_correlation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlation',
            name='like_new_id',
            field=models.CharField(max_length=20, verbose_name='相似新闻id'),
        ),
        migrations.AlterField(
            model_name='correlation',
            name='new_id',
            field=models.CharField(max_length=20, verbose_name='新闻id'),
        ),
        migrations.AlterField(
            model_name='correlation',
            name='similarity',
            field=models.CharField(max_length=20, verbose_name='相似度'),
        ),
    ]
