# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-05 00:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20191104_1743'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='新闻id', to='index.New')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='用户id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '收藏',
                'db_table': 'collection',
            },
        ),
    ]
