# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-05 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(default='要小心碌碌庸庸带来的空虚', max_length=100, null=True),
        ),
    ]
