# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-07 07:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20191106_2210'),
        ('users', '0003_auto_20191105_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000, verbose_name='评论内容')),
                ('now_time', models.DateTimeField(default=datetime.datetime(2019, 11, 7, 7, 58, 50, 140066, tzinfo=utc), verbose_name='时间')),
                ('new_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='被评论新闻id', to='index.New')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='评论用户id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
