# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-07 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='now_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间'),
        ),
    ]
