# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-07 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191107_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
